version: '3.7'
services:
  auth:
    container_name: auth
    image: ${AUTH_TAG}
    restart: always
    ports:
      - '6060:6060'
      - '6160:6160'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2048M'
    networks:
      - cinch
    environment:
      SERVICE_DATA_DATABASE_DSN: ${SERVICE_DATA_DATABASE_DSN}
      SERVICE_DATA_REDIS_DSN: ${SERVICE_DATA_REDIS_DSN}

networks:
  cinch:
    external: true
    name: cinch
