version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '2048M'
    networks:
      - cinch

  mysql:
    container_name: mysql
    image: mysql:8.0.19
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --default-authentication-plugin=mysql_native_password
      --max_allowed_packet=128M
      --slow_query_log=ON
      --long_query_time=1
      --log_queries_not_using_indexes=ON
      --log_output='FILE,TABLE'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2048M'
    networks:
      - cinch
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql/conf.d

volumes:
  mysql-data:
  mysql-conf:

networks:
  cinch:
    name: cinch
