version: '3.7'
services:
  pc-vue3:
    container_name: pc-vue3
    image: ${PC_VUE3_TAG}
    restart: always
    entrypoint: /opt/entrypoint.sh
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
      AUTH_HOST: ${AUTH_HOST}
      AUTH_PORT: ${AUTH_PORT}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1024M'
    networks:
      - cinch
    volumes:
      - ./nginx/entrypoint.sh:/opt/entrypoint.sh:ro
      - ./nginx/conf.d/cinch.tpl:/etc/nginx/conf.d/cinch.tpl:ro

networks:
  cinch:
    external: true
    name: cinch